# Generated by Django 5.0.1 on 2024-02-06 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Angajat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('varsta', models.IntegerField()),
                ('cnp', models.CharField(max_length=20)),
                ('telefon', models.CharField(max_length=20, null=True)),
                ('mail', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Adresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strada', models.CharField(max_length=100)),
                ('numar', models.CharField(max_length=10)),
                ('localitate', models.CharField(max_length=100)),
                ('judet', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('angajat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='angajati.angajat')),
            ],
        ),
        migrations.CreateModel(
            name='Concedii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('tip', models.CharField(max_length=2)),
                ('angajat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='angajati.angajat')),
            ],
        ),
        migrations.CreateModel(
            name='Salarii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suma', models.DecimalField(decimal_places=4, max_digits=6)),
                ('luna', models.IntegerField()),
                ('angajat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='angajati.angajat')),
            ],
        ),
    ]
