# Generated by Django 5.0.1 on 2024-02-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angajati', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='angajat',
            options={'ordering': ['-varsta', 'nume']},
        ),
        migrations.AlterField(
            model_name='angajat',
            name='mail',
            field=models.EmailField(max_length=50),
        ),
    ]
