# Generated by Django 5.0.1 on 2024-02-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angajati', '0002_alter_angajat_options_alter_angajat_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angajat',
            name='mail',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
