# Generated by Django 5.0.1 on 2024-02-06 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
                ('indicativ_judet', models.CharField(max_length=2)),
                ('populatie', models.IntegerField()),
                ('suprafata', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
                ('suprafata', models.IntegerField()),
                ('acoperit', models.BooleanField(default=False)),
                ('oras', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='zone_agrement.orase')),
            ],
        ),
        migrations.CreateModel(
            name='Tipuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
                ('opening_hours', models.DateTimeField()),
                ('closing_hours', models.DateTimeField()),
                ('players_nr', models.IntegerField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='zone_agrement.zone')),
            ],
        ),
    ]
