# Generated by Django 5.0.1 on 2024-02-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zone_agrement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipuri',
            new_name='TipuriLocatii',
        ),
    ]
