# Generated by Django 5.0.1 on 2024-02-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='numar_produse',
            field=models.IntegerField(null=True),
        ),
    ]
