# Generated by Django 5.0.1 on 2024-02-06 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parfumuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('greutate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('culoare', models.CharField(max_length=20, null=True)),
                ('descriere', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('gramaj', models.DecimalField(decimal_places=4, max_digits=6)),
                ('cost', models.DecimalField(decimal_places=4, max_digits=6)),
                ('parfum', models.ManyToManyField(to='parfumuri.parfumuri')),
            ],
        ),
        migrations.CreateModel(
            name='Producatori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('tara', models.CharField(max_length=100, null=True)),
                ('cui', models.IntegerField()),
                ('parfum', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parfumuri.parfumuri')),
            ],
        ),
    ]
